import type { Locale } from "@eve/widget-sdk";

export const lunarCopy = {
  vi: {
    title: "Âm lịch",
    description: "Ngày âm lịch hôm nay theo múi giờ bạn chọn.",
    leap: "nhuận",
    monthPrefix: "tháng",
    soc: "Sóc",
    ram: "Rằm",
    year: "Năm",
    month: "Tháng",
    day: "Ngày",
    solar: "Dương",
    phase: "Trăng",
    term: "Tiết",
    nextFull: "Rằm tới",
    nextNew: "Sóc tới",
    today: "hôm nay",
    daysUnit: "ngày",
    phaseNew: "Trăng non",
    phaseWaxingCrescent: "Lưỡi liềm",
    phaseFirstQuarter: "Thượng huyền",
    phaseWaxingGibbous: "Dần đầy",
    phaseFull: "Trăng tròn",
    phaseWaningGibbous: "Dần khuyết",
    phaseLastQuarter: "Hạ huyền",
    phaseWaningCrescent: "Trăng tàn",
  },
  en: {
    title: "Lunar Calendar",
    description: "Today's Vietnamese lunar date in the timezone you pick.",
    leap: "leap",
    monthPrefix: "month",
    soc: "New moon",
    ram: "Full moon",
    year: "Year",
    month: "Month",
    day: "Day",
    solar: "Solar",
    phase: "Moon",
    term: "Term",
    nextFull: "Full in",
    nextNew: "New in",
    today: "today",
    daysUnit: "days",
    phaseNew: "New",
    phaseWaxingCrescent: "Waxing crescent",
    phaseFirstQuarter: "First quarter",
    phaseWaxingGibbous: "Waxing gibbous",
    phaseFull: "Full",
    phaseWaningGibbous: "Waning gibbous",
    phaseLastQuarter: "Last quarter",
    phaseWaningCrescent: "Waning crescent",
  },
} as const satisfies Record<Locale, Record<string, string>>;
